autd3-freq-shift: autd::Result< T, E > Class Template Reference
autd::Result< T, E > Class Template Reference
#include <result.hpp>
Public Member Functions
bool is_ok () const
bool is_err () const
T unwrap ()
E unwrap_err ()
T unwrap_or (T v)
Static Public Member Functions
static Result Ok (T ok)
static Result Err (E err)
Detailed Description
template<class T, class E>
class autd::Result< T, E >
Definition at line 21 of file result.hpp.
Member Function Documentation
Err()
template<class T , class E > static Result autd::Result< T, E >::Err (E err) inline static
Definition at line 31 of file result.hpp.
Referenced by autd::ErrType< T >::operator Result< V, T >().
is_err()
template<class T , class E > bool autd::Result< T, E >::is_err () const inline
Definition at line 28 of file result.hpp.
Referenced by autd::Result< T, E >::unwrap(), and autd::Result< T, E >::unwrap_or().
is_ok()
template<class T , class E > bool autd::Result< T, E >::is_ok () const inline
Definition at line 27 of file result.hpp.
Referenced by autd::Result< T, E >::unwrap_err().
Ok()
template<class T , class E > static Result autd::Result< T, E >::Ok (T ok) inline static
Definition at line 30 of file result.hpp.
Referenced by autd::OkType< T >::operator Result< T, E >().
unwrap()
template<class T , class E > T autd::Result< T, E >::unwrap () inline
Definition at line 33 of file result.hpp.
References autd::Result< T, E >::is_err().
unwrap_err()
template<class T , class E > E autd::Result< T, E >::unwrap_err () inline
Definition at line 42 of file result.hpp.
References autd::Result< T, E >::is_ok().
unwrap_or()
template<class T , class E > T autd::Result< T, E >::unwrap_or (T v) inline
Definition at line 47 of file result.hpp.
References autd::Result< T, E >::is_err().
The documentation for this class was generated from the following file:
include/result.hpp