autd3-freq-shift: autd::utils::Vector3< T > Class Template Reference
autd::utils::Vector3< T > Class Template Reference
#include <vector.hpp>
Public Member Functions
Vector3 ()
Vector3 (T x, T y, T z)
Vector3 (const Vector3 &obj)
Vector3 & operator= (const Vector3 &obj)
Vector3 (const Vector3 &&obj) noexcept
Vector3 & operator= (Vector3 &&obj) noexcept
~Vector3 ()=default
T & x () noexcept
T & y () noexcept
T & z () noexcept
const T & x () const noexcept
const T & y () const noexcept
const T & z () const noexcept
Vector3 normalized () const
Vector3 cross (const Vector3 &rhs) const
T angle (const Vector3 &v) const
Vector3 & operator+= (const Vector3 &rhs)
Vector3 & operator-= (const Vector3 &rhs)
Vector3 & operator*= (const T &rhs)
Vector3 & operator/= (const T &rhs)
Vector3 operator- () const
Public Member Functions inherited from autd::utils::VectorX< T >
VectorX (const size_t size)
~VectorX ()=default
VectorX (const VectorX &obj)
VectorX & operator= (VectorX &obj)=delete
VectorX (VectorX &&obj) noexcept
VectorX & operator= (VectorX &&obj) noexcept
T l2_norm_squared () const
T l2_norm () const
T norm () const
void normalize ()
VectorX & normalized () const
T dot (const VectorX &rhs) const
T & at (size_t i)
const T & at (size_t i) const
T & operator() (size_t i)
const T & operator() (size_t i) const
T * data ()
const T * data () const
size_t size () const noexcept
VectorX & operator+= (const VectorX &rhs)
VectorX & operator-= (const VectorX &rhs)
VectorX & operator*= (T rhs)
VectorX & operator/= (T rhs)
VectorX operator- () const
Static Public Member Functions
static Vector3 UnitX ()
static Vector3 UnitY ()
static Vector3 UnitZ ()
static Vector3 Zero ()
Static Public Member Functions inherited from autd::utils::VectorX< T >
static VectorX Zero (size_t size)
static VectorX Ones (size_t size)
Friends
Vector3 operator+ (const Vector3 &lhs, const Vector3 &rhs)
Vector3 operator- (const Vector3 &lhs, const Vector3 &rhs)
Vector3 operator* (const Vector3 &lhs, const T &rhs)
Vector3 operator* (const T &lhs, const Vector3 &rhs)
Vector3 operator/ (const Vector3 &lhs, const T &rhs)
Detailed Description
template<typename T>
class autd::utils::Vector3< T >
Definition at line 108 of file vector.hpp.
Constructor & Destructor Documentation
Vector3() [1/4]
template<typename T > autd::utils::Vector3< T >::Vector3 () inline
Definition at line 110 of file vector.hpp.
Vector3() [2/4]
template<typename T > autd::utils::Vector3< T >::Vector3 (T x, T y, T z) inline
Definition at line 111 of file vector.hpp.
Vector3() [3/4]
template<typename T > autd::utils::Vector3< T >::Vector3 (const Vector3< T > & obj) inline
Definition at line 116 of file vector.hpp.
Vector3() [4/4]
template<typename T > autd::utils::Vector3< T >::Vector3 (const Vector3< T > && obj) inline noexcept
Definition at line 127 of file vector.hpp.
~Vector3()
template<typename T > autd::utils::Vector3< T >::~Vector3 () default
Member Function Documentation
angle()
template<typename T > T autd::utils::Vector3< T >::angle (const Vector3< T > & v) const inline
Definition at line 155 of file vector.hpp.
cross()
template<typename T > Vector3 autd::utils::Vector3< T >::cross (const Vector3< T > & rhs) const inline
Definition at line 151 of file vector.hpp.
normalized()
template<typename T > Vector3 autd::utils::Vector3< T >::normalized () const inline
Definition at line 149 of file vector.hpp.
operator*=()
template<typename T > Vector3& autd::utils::Vector3< T >::operator*= (const T & rhs) inline
Definition at line 170 of file vector.hpp.
operator+=()
template<typename T > Vector3& autd::utils::Vector3< T >::operator+= (const Vector3< T > & rhs) inline
Definition at line 168 of file vector.hpp.
operator-()
template<typename T > Vector3 autd::utils::Vector3< T >::operator- () const inline
Definition at line 173 of file vector.hpp.
operator-=()
template<typename T > Vector3& autd::utils::Vector3< T >::operator-= (const Vector3< T > & rhs) inline
Definition at line 169 of file vector.hpp.
operator/=()
template<typename T > Vector3& autd::utils::Vector3< T >::operator/= (const T & rhs) inline
Definition at line 171 of file vector.hpp.
operator=() [1/2]
template<typename T > Vector3& autd::utils::Vector3< T >::operator= (const Vector3< T > & obj) inline
Definition at line 117 of file vector.hpp.
operator=() [2/2]
template<typename T > Vector3& autd::utils::Vector3< T >::operator= (Vector3< T > && obj) inline noexcept
Definition at line 128 of file vector.hpp.
UnitX()
template<typename T > static Vector3 autd::utils::Vector3< T >::UnitX () inline static
Definition at line 144 of file vector.hpp.
UnitY()
template<typename T > static Vector3 autd::utils::Vector3< T >::UnitY () inline static
Definition at line 145 of file vector.hpp.
UnitZ()
template<typename T > static Vector3 autd::utils::Vector3< T >::UnitZ () inline static
Definition at line 146 of file vector.hpp.
x() [1/2]
template<typename T > const T& autd::utils::Vector3< T >::x () const inline noexcept
Definition at line 140 of file vector.hpp.
x() [2/2]
template<typename T > T& autd::utils::Vector3< T >::x () inline noexcept
Definition at line 137 of file vector.hpp.
Referenced by autd::Device::Create(), autd::utils::Vector3< Float >::cross(), autd::utils::Matrix4X4< T >::Translation(), and autd::utils::Quaternion< T >::x().
y() [1/2]
template<typename T > const T& autd::utils::Vector3< T >::y () const inline noexcept
Definition at line 141 of file vector.hpp.
y() [2/2]
template<typename T > T& autd::utils::Vector3< T >::y () inline noexcept
Definition at line 138 of file vector.hpp.
Referenced by autd::Device::Create(), autd::utils::Vector3< Float >::cross(), autd::utils::Matrix4X4< T >::Translation(), and autd::utils::Quaternion< T >::y().
z() [1/2]
template<typename T > const T& autd::utils::Vector3< T >::z () const inline noexcept
Definition at line 142 of file vector.hpp.
z() [2/2]
template<typename T > T& autd::utils::Vector3< T >::z () inline noexcept
Definition at line 139 of file vector.hpp.
Referenced by autd::Device::Create(), autd::utils::Vector3< Float >::cross(), autd::utils::Matrix4X4< T >::Translation(), and autd::utils::Quaternion< T >::z().
Zero()
template<typename T > static Vector3 autd::utils::Vector3< T >::Zero () inline static
Definition at line 147 of file vector.hpp.
Friends And Related Function Documentation
operator* [1/2]
template<typename T > Vector3 operator* (const T & lhs, const Vector3< T > & rhs) friend
Definition at line 179 of file vector.hpp.
operator* [2/2]
template<typename T > Vector3 operator* (const Vector3< T > & lhs, const T & rhs) friend
Definition at line 178 of file vector.hpp.
operator+
template<typename T > Vector3 operator+ (const Vector3< T > & lhs, const Vector3< T > & rhs) friend
Definition at line 175 of file vector.hpp.
operator-
template<typename T > Vector3 operator- (const Vector3< T > & lhs, const Vector3< T > & rhs) friend
Definition at line 177 of file vector.hpp.
operator/
template<typename T > Vector3 operator/ (const Vector3< T > & lhs, const T & rhs) friend
Definition at line 180 of file vector.hpp.
The documentation for this class was generated from the following file:
include/linalg/vector.hpp