autd3-freq-shift: autd::core::Gain Class Reference
autd::core::Gain Class Reference
Gain controls the duty ratio and phase of each transducer in AUTD devices.
#include <gain.hpp>
Public Member Functions
virtual void calc (const GeometryPtr &geometry)
Calculate duty ratio and phase of each transducer.
void build (const GeometryPtr &geometry)
Initialize data and call calc().
void rebuild (const GeometryPtr &geometry)
Re-calculate duty ratio and phase of each transducer.
const std::vector< DataArray > & duties () const noexcept
const std::vector< DataArray > & phases () const noexcept
Gain () noexcept
virtual ~Gain ()=default
Gain (const Gain &v) noexcept=default
Gain & operator= (const Gain &obj)=default
Gain (Gain &&obj)=default
Gain & operator= (Gain &&obj)=default
Static Public Member Functions
static GainPtr create ()
Generate empty gain.
Detailed Description
Gain controls the duty ratio and phase of each transducer in AUTD devices.
Definition at line 29 of file gain.hpp.
Constructor & Destructor Documentation
Gain() [1/3]
autd::core::Gain::Gain () inline noexcept
Definition at line 76 of file gain.hpp.
~Gain()
virtual autd::core::Gain::~Gain () virtual default
Gain() [2/3]
autd::core::Gain::Gain (const Gain & v) default noexcept
Gain() [3/3]
autd::core::Gain::Gain (Gain && obj) default
Member Function Documentation
build()
void autd::core::Gain::build (const GeometryPtr & geometry) inline
Initialize data and call calc().
Parameters
geometry Geometry
Definition at line 49 of file gain.hpp.
References calc().
Referenced by rebuild().
calc()
virtual void autd::core::Gain::calc (const GeometryPtr & geometry) inline virtual
Calculate duty ratio and phase of each transducer.
Parameters
geometry Geometry
Definition at line 40 of file gain.hpp.
Referenced by build().
create()
static GainPtr autd::core::Gain::create () inline static
Generate empty gain.
Definition at line 34 of file gain.hpp.
Referenced by autd::Controller::stop().
duties()
const std::vector<DataArray>& autd::core::Gain::duties () const inline noexcept
Definition at line 72 of file gain.hpp.
operator=() [1/2]
Gain& autd::core::Gain::operator= (const Gain & obj) default
operator=() [2/2]
Gain& autd::core::Gain::operator= (Gain && obj) default
phases()
const std::vector<DataArray>& autd::core::Gain::phases () const inline noexcept
Definition at line 74 of file gain.hpp.
rebuild()
void autd::core::Gain::rebuild (const GeometryPtr & geometry) inline
Re-calculate duty ratio and phase of each transducer.
Parameters
geometry Geometry
Definition at line 67 of file gain.hpp.
References build().
The documentation for this class was generated from the following file:
include/autd3-freq-shift/core/gain.hpp