autd3-freq-shift: autd::core::Logic Class Reference
autd::core::Logic Class Reference
Hardware logic.
#include <logic.hpp>
Static Public Member Functions
static bool is_msg_processed (const size_t num_devices, const uint8_t msg_id, const uint8_t *const rx)
check if the data which have msg_id have been processed in the devices.
static void pack_header (const COMMAND cmd, uint8_t *data, uint8_t *const msg_id)
Pack header with COMMAND.
static void pack_duty_body (const GainPtr &gain, uint8_t *data, size_t *size)
Pack data body which contain duty data of each transducer.
static void pack_phase_body (const GainPtr &gain, uint8_t *data, size_t *size)
Pack data body which contain phase data of each transducer.
static void pack_freq_body (const GeometryPtr &geometry, uint8_t *data, size_t *size)
Pack frequency body.
Detailed Description
Hardware logic.
Definition at line 26 of file logic.hpp.
Member Function Documentation
is_msg_processed()
static bool autd::core::Logic::is_msg_processed (const size_t num_devices, const uint8_t msg_id, const uint8_t *const rx) inline static
check if the data which have msg_id have been processed in the devices.
Parameters
num_devices number of devices
msg_id message id
rx pointer to received data
Returns
whether the data have been processed
Definition at line 45 of file logic.hpp.
pack_duty_body()
static void autd::core::Logic::pack_duty_body (const GainPtr & gain, uint8_t * data, size_t * size) inline static
Pack data body which contain duty data of each transducer.
Parameters
gain Gain
[out] data pointer to transmission data
[out] size size to send
Definition at line 71 of file logic.hpp.
References autd::core::NUM_TRANS_IN_UNIT.
Referenced by autd::Controller::send().
pack_freq_body()
static void autd::core::Logic::pack_freq_body (const GeometryPtr & geometry, uint8_t * data, size_t * size) inline static
Pack frequency body.
Parameters
geometry Geometry
[out] data pointer to transmission data
[out] size size to send
Definition at line 105 of file logic.hpp.
References autd::core::NUM_TRANS_IN_UNIT.
Referenced by autd::Controller::set_frequency().
pack_header()
static void autd::core::Logic::pack_header (const COMMAND cmd, uint8_t * data, uint8_t *const msg_id) inline static
Pack header with COMMAND.
Parameters
cmd command
[out] data pointer to transmission data
[out] msg_id message id
Definition at line 58 of file logic.hpp.
Referenced by autd::Controller::send(), and autd::Controller::set_frequency().
pack_phase_body()
static void autd::core::Logic::pack_phase_body (const GainPtr & gain, uint8_t * data, size_t * size) inline static
Pack data body which contain phase data of each transducer.
Parameters
gain Gain
[out] data pointer to transmission data
[out] size size to send
Definition at line 88 of file logic.hpp.
References autd::core::NUM_TRANS_IN_UNIT.
Referenced by autd::Controller::send().
The documentation for this class was generated from the following file:
include/autd3-freq-shift/core/logic.hpp