autd3-freq-shift: autd::utils::Matrix4X4< T > Class Template Reference
autd::utils::Matrix4X4< T > Class Template Reference
#include <matrix.hpp>
Public Member Functions
Matrix4X4 ()
Matrix4X4 & operator+= (const Matrix4X4 &rhs)
Matrix4X4 & operator-= (const Matrix4X4 &rhs)
Matrix4X4 & operator*= (const T &rhs)
Matrix4X4 & operator/= (const T &rhs)
Matrix4X4 operator- () const
Public Member Functions inherited from autd::utils::MatrixX< T >
MatrixX (const size_t row, const size_t col)
~MatrixX ()=default
MatrixX (const MatrixX &obj)
MatrixX & operator= (MatrixX &obj)=delete
MatrixX (MatrixX &&obj)=default
MatrixX & operator= (MatrixX &&obj)=default
T & at (const size_t row, const size_t col)
const T & at (const size_t row, const size_t col) const
T & operator() (const size_t row, const size_t col)
const T & operator() (const size_t row, const size_t col) const
T * data ()
const T * data () const
size_t rows () const noexcept
size_t cols () const noexcept
size_t size () const noexcept
VectorX< T > col (const size_t idx) const noexcept
VectorX< T > row (const size_t idx) const noexcept
MatrixX & operator+= (const MatrixX &rhs)
MatrixX & operator-= (const MatrixX &rhs)
MatrixX & operator*= (T rhs)
MatrixX & operator/= (T rhs)
MatrixX operator- () const
Static Public Member Functions
static Matrix4X4 Translation (const Vector3< T > &v, const Quaternion< T > &q)
Static Public Member Functions inherited from autd::utils::MatrixX< T >
static MatrixX Zero (size_t row, size_t col)
static MatrixX Identity (const size_t row, const size_t col)
Friends
Matrix4X4 operator+ (const Matrix4X4 &lhs, const Matrix4X4 &rhs)
Matrix4X4 operator- (const Matrix4X4 &lhs, const Matrix4X4 &rhs)
Matrix4X4 operator* (const Matrix4X4 &lhs, const T &rhs)
Matrix4X4 operator* (const T &lhs, Matrix4X4 rhs)
Matrix4X4 operator/ (const Matrix4X4 &lhs, const T &rhs)
Detailed Description
template<typename T>
class autd::utils::Matrix4X4< T >
Definition at line 115 of file matrix.hpp.
Constructor & Destructor Documentation
Matrix4X4()
template<typename T > autd::utils::Matrix4X4< T >::Matrix4X4 () inline
Definition at line 117 of file matrix.hpp.
Member Function Documentation
operator*=()
template<typename T > Matrix4X4& autd::utils::Matrix4X4< T >::operator*= (const T & rhs) inline
Definition at line 121 of file matrix.hpp.
operator+=()
template<typename T > Matrix4X4& autd::utils::Matrix4X4< T >::operator+= (const Matrix4X4< T > & rhs) inline
Definition at line 119 of file matrix.hpp.
operator-()
template<typename T > Matrix4X4 autd::utils::Matrix4X4< T >::operator- () const inline
Definition at line 124 of file matrix.hpp.
operator-=()
template<typename T > Matrix4X4& autd::utils::Matrix4X4< T >::operator-= (const Matrix4X4< T > & rhs) inline
Definition at line 120 of file matrix.hpp.
operator/=()
template<typename T > Matrix4X4& autd::utils::Matrix4X4< T >::operator/= (const T & rhs) inline
Definition at line 122 of file matrix.hpp.
Translation()
template<typename T > static Matrix4X4 autd::utils::Matrix4X4< T >::Translation (const Vector3< T > & v, const Quaternion< T > & q) inline static
Definition at line 133 of file matrix.hpp.
References autd::utils::Quaternion< T >::w(), autd::utils::Quaternion< T >::x(), autd::utils::Vector3< T >::x(), autd::utils::Quaternion< T >::y(), autd::utils::Vector3< T >::y(), autd::utils::Quaternion< T >::z(), and autd::utils::Vector3< T >::z().
Referenced by autd::Device::Create().
Friends And Related Function Documentation
operator* [1/2]
template<typename T > Matrix4X4 operator* (const Matrix4X4< T > & lhs, const T & rhs) friend
Definition at line 129 of file matrix.hpp.
operator* [2/2]
template<typename T > Matrix4X4 operator* (const T & lhs, Matrix4X4< T > rhs) friend
Definition at line 130 of file matrix.hpp.
operator+
template<typename T > Matrix4X4 operator+ (const Matrix4X4< T > & lhs, const Matrix4X4< T > & rhs) friend
Definition at line 126 of file matrix.hpp.
operator-
template<typename T > Matrix4X4 operator- (const Matrix4X4< T > & lhs, const Matrix4X4< T > & rhs) friend
Definition at line 128 of file matrix.hpp.
operator/
template<typename T > Matrix4X4 operator/ (const Matrix4X4< T > & lhs, const T & rhs) friend
Definition at line 131 of file matrix.hpp.
The documentation for this class was generated from the following file:
include/linalg/matrix.hpp