autd3-freq-shift: autd::Controller Class Reference
autd::Controller Class Reference
#include <controller.hpp>
Public Member Functions
Controller ()
~Controller ()
void AddDevices (Device device, uint16_t freq_cycle=FPGA_BASE_CLK_FREQ/40000)
std::vector< Device > & devices ()
std::vector< uint16_t > & freq_cycles ()
size_t num_devices ()
Result< bool, std::string > OpenWith (LinkPtr link)
Result< bool, std::string > Close ()
Result< bool, std::string > Clear ()
Result< bool, std::string > Stop ()
Result< bool, std::string > SetFreqCycles ()
Result< bool, std::string > SendBlocking (GainPtr gain)
Result< std::vector< FirmwareInfo >, std::string > firmware_info_list ()
Static Public Member Functions
static ControllerPtr Create ()
Detailed Description
Definition at line 46 of file controller.hpp.
Constructor & Destructor Documentation
Controller()
autd::Controller::Controller () inline
Definition at line 50 of file controller.hpp.
~Controller()
autd::Controller::~Controller () inline
Definition at line 51 of file controller.hpp.
References Close().
Member Function Documentation
AddDevices()
void autd::Controller::AddDevices (Device device, uint16_t freq_cycle = FPGA_BASE_CLK_FREQ / 40000) inline
Definition at line 61 of file controller.hpp.
Clear()
Result<bool, std::string> autd::Controller::Clear () inline
Definition at line 86 of file controller.hpp.
References autd::CMD_CLEAR.
Referenced by Close().
Close()
Result<bool, std::string> autd::Controller::Close () inline
Definition at line 76 of file controller.hpp.
References Clear(), autd::Ok(), and Stop().
Referenced by ~Controller().
Create()
static ControllerPtr autd::Controller::Create () inline static
Definition at line 48 of file controller.hpp.
devices()
std::vector<Device>& autd::Controller::devices () inline
Definition at line 66 of file controller.hpp.
firmware_info_list()
Result<std::vector<FirmwareInfo>, std::string> autd::Controller::firmware_info_list () inline
Definition at line 112 of file controller.hpp.
References autd::CMD_READ_CPU_VER_LSB, autd::CMD_READ_CPU_VER_MSB, autd::CMD_READ_FPGA_VER_LSB, autd::CMD_READ_FPGA_VER_MSB, autd::Err(), and autd::Ok().
freq_cycles()
std::vector<uint16_t>& autd::Controller::freq_cycles () inline
Definition at line 67 of file controller.hpp.
num_devices()
size_t autd::Controller::num_devices () inline
Definition at line 69 of file controller.hpp.
OpenWith()
Result<bool, std::string> autd::Controller::OpenWith (LinkPtr link) inline
Definition at line 71 of file controller.hpp.
SendBlocking()
Result<bool, std::string> autd::Controller::SendBlocking (GainPtr gain) inline
Definition at line 96 of file controller.hpp.
Referenced by SetFreqCycles(), and Stop().
SetFreqCycles()
Result<bool, std::string> autd::Controller::SetFreqCycles () inline
Definition at line 90 of file controller.hpp.
References SendBlocking().
Stop()
Result<bool, std::string> autd::Controller::Stop () inline
Definition at line 88 of file controller.hpp.
References autd::Gain::Create(), and SendBlocking().
Referenced by Close().
The documentation for this class was generated from the following file:
include/controller.hpp