autd3-freq-shift: autd::Gain Class Reference
autd::Gain Class Reference
Gain controls the amplitude and phase of each transducer in the AUTD.
#include <gain.hpp>
Public Member Functions
virtual Result< bool, std::string > Build (std::vector< Device > &devices, std::vector< uint16_t > &freq_cycle)
Calculate amplitude and phase of each transducer.
virtual Result< bool, std::string > Rebuild (std::vector< Device > &devices, std::vector< uint16_t > &freq_cycle)
Re-calculate amplitude and phase of each transducer.
std::vector< AUTDDataArray > & duty ()
Getter function for the duty of amplitude and phase of each transducers.
std::vector< AUTDDataArray > & phase ()
Getter function for the phase of amplitude and phase of each transducers.
Gain () noexcept
virtual ~Gain ()=default
Gain (const Gain &v) noexcept=default
Gain & operator= (const Gain &obj)=default
Gain (Gain &&obj)=default
Gain & operator= (Gain &&obj)=default
Static Public Member Functions
static uint8_t ToDuty (const Float amp) noexcept
static void CheckAndInit (const std::vector< Device > &devices, std::vector< AUTDDataArray > *duty, std::vector< AUTDDataArray > *phase)
static GainPtr Create ()
Generate empty gain.
Detailed Description
Gain controls the amplitude and phase of each transducer in the AUTD.
Definition at line 33 of file gain.hpp.
Constructor & Destructor Documentation
Gain() [1/3]
autd::Gain::Gain () inline noexcept
Definition at line 91 of file gain.hpp.
~Gain()
virtual autd::Gain::~Gain () virtual default
Gain() [2/3]
autd::Gain::Gain (const Gain & v) default noexcept
Gain() [3/3]
autd::Gain::Gain (Gain && obj) default
Member Function Documentation
Build()
virtual Result<bool, std::string> autd::Gain::Build (std::vector< Device > & devices, std::vector< uint16_t > & freq_cycle) inline virtual
Calculate amplitude and phase of each transducer.
Definition at line 59 of file gain.hpp.
References CheckAndInit(), and autd::Ok().
Referenced by Rebuild().
CheckAndInit()
static void autd::Gain::CheckAndInit (const std::vector< Device > & devices, std::vector< AUTDDataArray > * duty, std::vector< AUTDDataArray > * phase) inline static
Definition at line 40 of file gain.hpp.
References duty(), and phase().
Referenced by Build().
Create()
static GainPtr autd::Gain::Create () inline static
Generate empty gain.
Definition at line 54 of file gain.hpp.
Referenced by autd::Controller::Stop().
duty()
std::vector<AUTDDataArray>& autd::Gain::duty () inline
Getter function for the duty of amplitude and phase of each transducers.
Each duty is 16 bit unsigned integer
Definition at line 83 of file gain.hpp.
Referenced by CheckAndInit().
operator=() [1/2]
Gain& autd::Gain::operator= (const Gain & obj) default
operator=() [2/2]
Gain& autd::Gain::operator= (Gain && obj) default
phase()
std::vector<AUTDDataArray>& autd::Gain::phase () inline
Getter function for the phase of amplitude and phase of each transducers.
Each phase is 16 bit unsigned integer
Definition at line 89 of file gain.hpp.
Referenced by CheckAndInit().
Rebuild()
virtual Result<bool, std::string> autd::Gain::Rebuild (std::vector< Device > & devices, std::vector< uint16_t > & freq_cycle) inline virtual
Re-calculate amplitude and phase of each transducer.
Definition at line 74 of file gain.hpp.
References Build().
ToDuty()
static uint8_t autd::Gain::ToDuty (const Float amp) inline static noexcept
Definition at line 35 of file gain.hpp.
References autd::PI.
The documentation for this class was generated from the following file:
include/gain.hpp