autd3-freq-shift: autd::core::Timer< T > Class Template Reference
autd::core::Timer< T > Class Template Reference
#include <timer.hpp>
Public Member Functions
Timer (std::unique_ptr< T > handler, const timer_t timer_id)
~Timer ()
std::unique_ptr< T > stop ()
Timer (const Timer &)=delete
Timer (Timer &&)=delete
Timer & operator= (const Timer &)=delete
Timer & operator= (Timer &&)=delete
Timer (std::unique_ptr< T > handler, dispatch_queue_t queue, dispatch_source_t timer)
~Timer ()
std::unique_ptr< T > stop ()
Timer (const Timer &)=delete
Timer (Timer &&)=delete
Timer & operator= (const Timer &)=delete
Timer & operator= (Timer &&)=delete
Timer (std::unique_ptr< T > handler, const uint32_t timer_id)
~Timer ()
std::unique_ptr< T > stop ()
Timer (const Timer &)=delete
Timer (Timer &&)=delete
Timer & operator= (const Timer &)=delete
Timer & operator= (Timer &&)=delete
Static Public Member Functions
static std::unique_ptr< Timer > start (std::unique_ptr< T > handler, const uint32_t interval_us)
static std::unique_ptr< Timer > start (std::unique_ptr< T > handler, const uint32_t interval_us)
static std::unique_ptr< Timer > start (std::unique_ptr< T > handler, uint32_t interval_us)
Detailed Description
template<typename T>
class autd::core::Timer< T >
Definition at line 28 of file timer.hpp.
Constructor & Destructor Documentation
Timer() [1/9]
template<typename T > autd::core::Timer< T >::Timer (std::unique_ptr< T > handler, const timer_t timer_id) inline
Definition at line 30 of file timer.hpp.
~Timer() [1/3]
template<typename T > autd::core::Timer< T >::~Timer () inline
Definition at line 31 of file timer.hpp.
References autd::core::Timer< T >::stop().
Timer() [2/9]
template<typename T > autd::core::Timer< T >::Timer (const Timer< T > &) delete
Timer() [3/9]
template<typename T > autd::core::Timer< T >::Timer (Timer< T > &&) delete
Timer() [4/9]
template<typename T > autd::core::Timer< T >::Timer (std::unique_ptr< T > handler, dispatch_queue_t queue, dispatch_source_t timer) inline
Definition at line 28 of file timer.hpp.
~Timer() [2/3]
template<typename T > autd::core::Timer< T >::~Timer () inline
Definition at line 30 of file timer.hpp.
References autd::core::Timer< T >::stop().
Timer() [5/9]
template<typename T > autd::core::Timer< T >::Timer (const Timer< T > &) delete
Timer() [6/9]
template<typename T > autd::core::Timer< T >::Timer (Timer< T > &&) delete
Timer() [7/9]
template<typename T > autd::core::Timer< T >::Timer (std::unique_ptr< T > handler, const uint32_t timer_id) inline
Definition at line 29 of file timer.hpp.
~Timer() [3/3]
template<typename T > autd::core::Timer< T >::~Timer () inline
Definition at line 30 of file timer.hpp.
References autd::core::Timer< T >::stop().
Timer() [8/9]
template<typename T > autd::core::Timer< T >::Timer (const Timer< T > &) delete
Timer() [9/9]
template<typename T > autd::core::Timer< T >::Timer (Timer< T > &&) delete
Member Function Documentation
operator=() [1/6]
template<typename T > Timer& autd::core::Timer< T >::operator= (const Timer< T > &) delete
operator=() [2/6]
template<typename T > Timer& autd::core::Timer< T >::operator= (const Timer< T > &) delete
operator=() [3/6]
template<typename T > Timer& autd::core::Timer< T >::operator= (const Timer< T > &) delete
operator=() [4/6]
template<typename T > Timer& autd::core::Timer< T >::operator= (Timer< T > &&) delete
operator=() [5/6]
template<typename T > Timer& autd::core::Timer< T >::operator= (Timer< T > &&) delete
operator=() [6/6]
template<typename T > Timer& autd::core::Timer< T >::operator= (Timer< T > &&) delete
start() [1/3]
template<typename T > static std::unique_ptr<Timer> autd::core::Timer< T >::start (std::unique_ptr< T > handler, const uint32_t interval_us) inline static
Definition at line 31 of file timer.hpp.
References autd::core::Timer< T >::start().
start() [2/3]
template<typename T > static std::unique_ptr<Timer> autd::core::Timer< T >::start (std::unique_ptr< T > handler, const uint32_t interval_us) inline static
Definition at line 32 of file timer.hpp.
Referenced by autd::core::Timer< T >::start().
start() [3/3]
template<typename T > static std::unique_ptr<Timer> autd::core::Timer< T >::start (std::unique_ptr< T > handler, uint32_t interval_us) inline static
Definition at line 32 of file timer.hpp.
stop() [1/3]
template<typename T > std::unique_ptr<T> autd::core::Timer< T >::stop () inline
Definition at line 48 of file timer.hpp.
stop() [2/3]
template<typename T > std::unique_ptr<T> autd::core::Timer< T >::stop () inline
Definition at line 52 of file timer.hpp.
stop() [3/3]
template<typename T > std::unique_ptr<T> autd::core::Timer< T >::stop () inline
Definition at line 53 of file timer.hpp.
Referenced by autd::core::Timer< T >::~Timer().
The documentation for this class was generated from the following file:
include/autd3-freq-shift/core/osal_timer/linux/timer.hpp