autd3-freq-shift: autd::core::Geometry Class Reference
autd::core::Geometry Class Reference
Geometry of all devices.
#include <geometry.hpp>
Public Member Functions
Geometry ()
~Geometry ()=default
Geometry (const Geometry &v) noexcept=default
Geometry & operator= (const Geometry &obj)=default
Geometry (Geometry &&obj)=default
Geometry & operator= (Geometry &&obj)=default
size_t add_device (const Vector3 &position, const Vector3 &euler_angles, const uint16_t freq_cycle=FPGA_BASE_CLK_FREQ/40000)
Add new device with position and rotation. Note that the transform is done with order: Translate -> Rotate.
size_t add_device (const Vector3 &position, const Quaternion &quaternion, const uint16_t freq_cycle=FPGA_BASE_CLK_FREQ/40000)
Same as add_device(const Vector3&, const Vector3&, const size_t), but using quaternion rather than zyz euler angles.
size_t del_device (const size_t idx)
Delete device.
void clear_devices ()
Clear all devices.
double & sound_speed () noexcept
Speed of sound.
double wavelength (const size_t dev_idx) const
ultrasound wavelength
size_t num_devices () const noexcept
Number of devices.
size_t num_transducers () const noexcept
Number of transducers.
uint16_t freq_cycle (const size_t device_idx) const
double frequency (const size_t device_idx) const
const Vector3 & position (const size_t global_transducer_idx) const
Position of a transducer specified by id.
const Vector3 & position (const size_t device_idx, const size_t local_transducer_idx) const
Position of a transducer specified by id.
Vector3 to_local_position (const size_t device_idx, const Vector3 &global_position) const
Convert a global position to a local position.
const Vector3 & direction (const size_t device_idx) const
Normalized direction of a device.
const Vector3 & x_direction (const size_t device_idx) const
Normalized long-axis direction of a device.
const Vector3 & y_direction (const size_t device_idx) const
Normalized short-axis direction of a device.
const Vector3 & z_direction (const size_t device_idx) const
Same as the direction()
Static Public Member Functions
static size_t device_idx_for_trans_idx (const size_t transducer_idx)
Convert transducer index into device index.
Detailed Description
Geometry of all devices.
Definition at line 87 of file geometry.hpp.
Constructor & Destructor Documentation
Geometry() [1/3]
autd::core::Geometry::Geometry () inline
Definition at line 89 of file geometry.hpp.
~Geometry()
autd::core::Geometry::~Geometry () default
Geometry() [2/3]
autd::core::Geometry::Geometry (const Geometry & v) default noexcept
Geometry() [3/3]
autd::core::Geometry::Geometry (Geometry && obj) default
Member Function Documentation
add_device() [1/2]
size_t autd::core::Geometry::add_device (const Vector3 & position, const Quaternion & quaternion, const uint16_t freq_cycle = FPGA_BASE_CLK_FREQ / 40000) inline
Same as add_device(const Vector3&, const Vector3&, const size_t), but using quaternion rather than zyz euler angles.
Parameters
position Position of transducer #0, which is the one at the lower-left corner.
quaternion rotation quaternion of the device.
freq_cycle frequency will be FPGA_BASE_CLK_FREQ / freq_cycle
Returns
an id of added device
Definition at line 117 of file geometry.hpp.
References freq_cycle(), and position().
add_device() [2/2]
size_t autd::core::Geometry::add_device (const Vector3 & position, const Vector3 & euler_angles, const uint16_t freq_cycle = FPGA_BASE_CLK_FREQ / 40000) inline
Add new device with position and rotation. Note that the transform is done with order: Translate -> Rotate.
Parameters
position Position of transducer #0, which is the one at the lower-left corner. (The lower-left corner is the one with the two missing transducers.)
euler_angles ZYZ convention euler angle of the device
freq_cycle frequency will be FPGA_BASE_CLK_FREQ / freq_cycle
Returns
an id of added device
Definition at line 104 of file geometry.hpp.
References freq_cycle(), and position().
clear_devices()
void autd::core::Geometry::clear_devices () inline
Clear all devices.
Definition at line 136 of file geometry.hpp.
del_device()
size_t autd::core::Geometry::del_device (const size_t idx) inline
Delete device.
Parameters
idx Index of the device to delete
Returns
an index of deleted device
Definition at line 128 of file geometry.hpp.
device_idx_for_trans_idx()
static size_t autd::core::Geometry::device_idx_for_trans_idx (const size_t transducer_idx) inline static
Convert transducer index into device index.
Definition at line 211 of file geometry.hpp.
References autd::core::NUM_TRANS_IN_UNIT.
Referenced by position().
direction()
const Vector3& autd::core::Geometry::direction (const size_t device_idx) const inline
Normalized direction of a device.
Definition at line 191 of file geometry.hpp.
freq_cycle()
uint16_t autd::core::Geometry::freq_cycle (const size_t device_idx) const inline
Definition at line 158 of file geometry.hpp.
Referenced by add_device(), and frequency().
frequency()
double autd::core::Geometry::frequency (const size_t device_idx) const inline
Definition at line 160 of file geometry.hpp.
References autd::core::FPGA_BASE_CLK_FREQ, and freq_cycle().
Referenced by wavelength().
num_devices()
size_t autd::core::Geometry::num_devices () const inline noexcept
Number of devices.
Definition at line 151 of file geometry.hpp.
Referenced by num_transducers().
num_transducers()
size_t autd::core::Geometry::num_transducers () const inline noexcept
Number of transducers.
Definition at line 156 of file geometry.hpp.
References num_devices(), and autd::core::NUM_TRANS_IN_UNIT.
operator=() [1/2]
Geometry& autd::core::Geometry::operator= (const Geometry & obj) default
operator=() [2/2]
Geometry& autd::core::Geometry::operator= (Geometry && obj) default
position() [1/2]
const Vector3& autd::core::Geometry::position (const size_t device_idx, const size_t local_transducer_idx) const inline
Position of a transducer specified by id.
Definition at line 175 of file geometry.hpp.
position() [2/2]
const Vector3& autd::core::Geometry::position (const size_t global_transducer_idx) const inline
Position of a transducer specified by id.
Definition at line 167 of file geometry.hpp.
References device_idx_for_trans_idx(), and autd::core::NUM_TRANS_IN_UNIT.
Referenced by add_device().
sound_speed()
double& autd::core::Geometry::sound_speed () inline noexcept
Speed of sound.
Definition at line 141 of file geometry.hpp.
to_local_position()
Vector3 autd::core::Geometry::to_local_position (const size_t device_idx, const Vector3 & global_position) const inline
Convert a global position to a local position.
Definition at line 182 of file geometry.hpp.
wavelength()
double autd::core::Geometry::wavelength (const size_t dev_idx) const inline
ultrasound wavelength
Definition at line 146 of file geometry.hpp.
References frequency().
x_direction()
const Vector3& autd::core::Geometry::x_direction (const size_t device_idx) const inline
Normalized long-axis direction of a device.
Definition at line 196 of file geometry.hpp.
y_direction()
const Vector3& autd::core::Geometry::y_direction (const size_t device_idx) const inline
Normalized short-axis direction of a device.
Definition at line 201 of file geometry.hpp.
z_direction()
const Vector3& autd::core::Geometry::z_direction (const size_t device_idx) const inline
Same as the direction()
Definition at line 206 of file geometry.hpp.
The documentation for this class was generated from the following file:
include/autd3-freq-shift/core/geometry.hpp