autd3-freq-shift: autd::utils::Quaternion< T > Class Template Reference
autd::utils::Quaternion< T > Class Template Reference
Simple quaternion class.
#include <quaternion.hpp>
Public Member Functions
Quaternion ()=default
~Quaternion ()=default
Quaternion (T w, T x, T y, T z)
Quaternion (T w, const Vector3< T > &v)
Quaternion (const Quaternion &obj)
Quaternion & operator= (const Quaternion &obj)
Quaternion (const Quaternion &&obj) noexcept
Quaternion & operator= (Quaternion &&obj) noexcept
Vector3< T > & v () noexcept
const Vector3< T > & v () const noexcept
T & x () noexcept
T & y () noexcept
T & z () noexcept
T & w () noexcept
const T & x () const noexcept
const T & y () const noexcept
const T & z () const noexcept
const T & w () const noexcept
T l2_norm_squared () const
T l2_norm () const
T norm () const
Quaternion normalized () const
Quaternion conjugate () const
Quaternion inverse () const
Quaternion & operator+= (const Quaternion &rhs)
Quaternion & operator-= (const Quaternion &rhs)
Quaternion & operator*= (T rhs)
Quaternion & operator/= (T rhs)
Static Public Member Functions
static Quaternion AngleAxis (T a, const Vector3< T > &v)
Friends
Quaternion operator* (Quaternion lhs, const Quaternion &rhs)
Vector3< T > operator* (Quaternion lhs, const Vector3< T > &rhs)
template<typename Ts >
std::ostream & operator<< (std::ostream &, const Quaternion< Ts > &)
template<typename Ts >
bool operator== (const Quaternion< Ts > &lhs, const Quaternion< Ts > &rhs)
template<typename Ts >
bool operator!= (const Quaternion< Ts > &lhs, const Quaternion< Ts > &rhs)
Quaternion operator+ (Quaternion lhs, const Quaternion &rhs)
Quaternion operator- (Quaternion lhs, const Quaternion &rhs)
Quaternion operator* (Quaternion lhs, const T &rhs)
Quaternion operator* (const T &lhs, Quaternion rhs)
Quaternion operator/ (Quaternion lhs, const T &rhs)
Detailed Description
template<typename T>
class autd::utils::Quaternion< T >
Simple quaternion class.
Definition at line 24 of file quaternion.hpp.
Constructor & Destructor Documentation
Quaternion() [1/5]
template<typename T > autd::utils::Quaternion< T >::Quaternion () default
Referenced by autd::utils::Quaternion< T >::AngleAxis().
~Quaternion()
template<typename T > autd::utils::Quaternion< T >::~Quaternion () default
Quaternion() [2/5]
template<typename T > autd::utils::Quaternion< T >::Quaternion (T w, T x, T y, T z) inline
Definition at line 31 of file quaternion.hpp.
References autd::utils::Quaternion< T >::w(), autd::utils::Quaternion< T >::x(), autd::utils::Quaternion< T >::y(), and autd::utils::Quaternion< T >::z().
Quaternion() [3/5]
template<typename T > autd::utils::Quaternion< T >::Quaternion (T w, const Vector3< T > & v) inline
Definition at line 35 of file quaternion.hpp.
References autd::utils::Quaternion< T >::v(), and autd::utils::Quaternion< T >::w().
Quaternion() [4/5]
template<typename T > autd::utils::Quaternion< T >::Quaternion (const Quaternion< T > & obj) inline
Definition at line 39 of file quaternion.hpp.
Quaternion() [5/5]
template<typename T > autd::utils::Quaternion< T >::Quaternion (const Quaternion< T > && obj) inline noexcept
Definition at line 45 of file quaternion.hpp.
Member Function Documentation
AngleAxis()
template<typename T > static Quaternion autd::utils::Quaternion< T >::AngleAxis (T a, const Vector3< T > & v) inline static
Definition at line 92 of file quaternion.hpp.
References autd::utils::Quaternion< T >::normalized(), autd::utils::Quaternion< T >::Quaternion(), and autd::utils::Quaternion< T >::v().
Referenced by autd::Device::Create().
conjugate()
template<typename T > Quaternion autd::utils::Quaternion< T >::conjugate () const inline
Definition at line 70 of file quaternion.hpp.
Referenced by autd::utils::Quaternion< T >::inverse().
inverse()
template<typename T > Quaternion autd::utils::Quaternion< T >::inverse () const inline
Definition at line 76 of file quaternion.hpp.
References autd::utils::Quaternion< T >::conjugate(), and autd::utils::Quaternion< T >::l2_norm_squared().
l2_norm()
template<typename T > T autd::utils::Quaternion< T >::l2_norm () const inline
Definition at line 66 of file quaternion.hpp.
References autd::utils::Quaternion< T >::l2_norm_squared().
Referenced by autd::utils::Quaternion< T >::norm(), and autd::utils::Quaternion< T >::normalized().
l2_norm_squared()
template<typename T > T autd::utils::Quaternion< T >::l2_norm_squared () const inline
Definition at line 65 of file quaternion.hpp.
References autd::utils::VectorX< T >::l2_norm_squared().
Referenced by autd::utils::Quaternion< T >::inverse(), and autd::utils::Quaternion< T >::l2_norm().
norm()
template<typename T > T autd::utils::Quaternion< T >::norm () const inline
Definition at line 67 of file quaternion.hpp.
References autd::utils::Quaternion< T >::l2_norm().
normalized()
template<typename T > Quaternion autd::utils::Quaternion< T >::normalized () const inline
Definition at line 69 of file quaternion.hpp.
References autd::utils::Quaternion< T >::l2_norm().
Referenced by autd::utils::Quaternion< T >::AngleAxis().
operator*=()
template<typename T > Quaternion& autd::utils::Quaternion< T >::operator*= (T rhs) inline
Definition at line 120 of file quaternion.hpp.
operator+=()
template<typename T > Quaternion& autd::utils::Quaternion< T >::operator+= (const Quaternion< T > & rhs) inline
Definition at line 110 of file quaternion.hpp.
References autd::utils::Quaternion< T >::v(), and autd::utils::Quaternion< T >::w().
operator-=()
template<typename T > Quaternion& autd::utils::Quaternion< T >::operator-= (const Quaternion< T > & rhs) inline
Definition at line 115 of file quaternion.hpp.
References autd::utils::Quaternion< T >::v(), and autd::utils::Quaternion< T >::w().
operator/=()
template<typename T > Quaternion& autd::utils::Quaternion< T >::operator/= (T rhs) inline
Definition at line 125 of file quaternion.hpp.
operator=() [1/2]
template<typename T > Quaternion& autd::utils::Quaternion< T >::operator= (const Quaternion< T > & obj) inline
Definition at line 40 of file quaternion.hpp.
operator=() [2/2]
template<typename T > Quaternion& autd::utils::Quaternion< T >::operator= (Quaternion< T > && obj) inline noexcept
Definition at line 46 of file quaternion.hpp.
v() [1/2]
template<typename T > const Vector3<T>& autd::utils::Quaternion< T >::v () const inline noexcept
Definition at line 55 of file quaternion.hpp.
v() [2/2]
template<typename T > Vector3<T>& autd::utils::Quaternion< T >::v () inline noexcept
Definition at line 54 of file quaternion.hpp.
Referenced by autd::utils::Quaternion< T >::AngleAxis(), autd::utils::Quaternion< T >::operator+=(), autd::utils::Quaternion< T >::operator-=(), autd::utils::operator==(), and autd::utils::Quaternion< T >::Quaternion().
w() [1/2]
template<typename T > const T& autd::utils::Quaternion< T >::w () const inline noexcept
Definition at line 63 of file quaternion.hpp.
w() [2/2]
template<typename T > T& autd::utils::Quaternion< T >::w () inline noexcept
Definition at line 59 of file quaternion.hpp.
Referenced by autd::utils::Quaternion< T >::operator+=(), autd::utils::Quaternion< T >::operator-=(), autd::utils::operator<<(), autd::utils::operator==(), autd::utils::Quaternion< T >::Quaternion(), and autd::utils::Matrix4X4< T >::Translation().
x() [1/2]
template<typename T > const T& autd::utils::Quaternion< T >::x () const inline noexcept
Definition at line 60 of file quaternion.hpp.
References autd::utils::Vector3< T >::x().
x() [2/2]
template<typename T > T& autd::utils::Quaternion< T >::x () inline noexcept
Definition at line 56 of file quaternion.hpp.
References autd::utils::Vector3< T >::x().
Referenced by autd::utils::operator<<(), autd::utils::Quaternion< T >::Quaternion(), and autd::utils::Matrix4X4< T >::Translation().
y() [1/2]
template<typename T > const T& autd::utils::Quaternion< T >::y () const inline noexcept
Definition at line 61 of file quaternion.hpp.
References autd::utils::Vector3< T >::y().
y() [2/2]
template<typename T > T& autd::utils::Quaternion< T >::y () inline noexcept
Definition at line 57 of file quaternion.hpp.
References autd::utils::Vector3< T >::y().
Referenced by autd::utils::operator<<(), autd::utils::Quaternion< T >::Quaternion(), and autd::utils::Matrix4X4< T >::Translation().
z() [1/2]
template<typename T > const T& autd::utils::Quaternion< T >::z () const inline noexcept
Definition at line 62 of file quaternion.hpp.
References autd::utils::Vector3< T >::z().
z() [2/2]
template<typename T > T& autd::utils::Quaternion< T >::z () inline noexcept
Definition at line 58 of file quaternion.hpp.
References autd::utils::Vector3< T >::z().
Referenced by autd::utils::operator<<(), autd::utils::Quaternion< T >::Quaternion(), and autd::utils::Matrix4X4< T >::Translation().
Friends And Related Function Documentation
operator!=
template<typename T > template<typename Ts > bool operator!= (const Quaternion< Ts > & lhs, const Quaternion< Ts > & rhs) friend
operator* [1/4]
template<typename T > Quaternion operator* (const T & lhs, Quaternion< T > rhs) friend
Definition at line 143 of file quaternion.hpp.
operator* [2/4]
template<typename T > Quaternion operator* (Quaternion< T > lhs, const Quaternion< T > & rhs) friend
Definition at line 78 of file quaternion.hpp.
operator* [3/4]
template<typename T > Quaternion operator* (Quaternion< T > lhs, const T & rhs) friend
Definition at line 139 of file quaternion.hpp.
operator* [4/4]
template<typename T > Vector3<T> operator* (Quaternion< T > lhs, const Vector3< T > & rhs) friend
Definition at line 86 of file quaternion.hpp.
operator+
template<typename T > Quaternion operator+ (Quaternion< T > lhs, const Quaternion< T > & rhs) friend
Definition at line 131 of file quaternion.hpp.
operator-
template<typename T > Quaternion operator- (Quaternion< T > lhs, const Quaternion< T > & rhs) friend
Definition at line 135 of file quaternion.hpp.
operator/
template<typename T > Quaternion operator/ (Quaternion< T > lhs, const T & rhs) friend
Definition at line 147 of file quaternion.hpp.
operator<<
template<typename T > template<typename Ts > std::ostream& operator<< (std::ostream & , const Quaternion< Ts > &) friend
operator==
template<typename T > template<typename Ts > bool operator== (const Quaternion< Ts > & lhs, const Quaternion< Ts > & rhs) friend
The documentation for this class was generated from the following file:
include/linalg/quaternion.hpp