autd3-freq-shift: autd Namespace Reference
autd Namespace Reference
Namespaces
utils
Classes
class Controller
struct Device
struct ErrType
class FirmwareInfo
Firmware information.
class Gain
Gain controls the amplitude and phase of each transducer in the AUTD.
class Link
Link is the interface to the AUTD device.
class LinkConfiguration
struct OkType
class Result
struct RxGlobalHeader
Typedefs
using Float = float
using AUTDDataArray = std::array< uint16_t, NUM_TRANS_IN_UNIT >
using ControllerPtr = unique_ptr< Controller >
using GainPtr = std::shared_ptr< Gain >
using NullGain = Gain
using Vector3 = utils::Vector3< Float >
using Vector4 = utils::Vector4< Float >
using Matrix4X4 = utils::Matrix4X4< Float >
using Quaternion = utils::Quaternion< Float >
using LinkPtr = std::unique_ptr< Link >
Enumerations
enum RX_GLOBAL_CONTROL_FLAGS : uint8_t { RX_GLOBAL_CONTROL_FLAGS::NONE = 0, RX_GLOBAL_CONTROL_FLAGS::FORCE_FAN = 1 << 4 }
Functions
constexpr RX_GLOBAL_CONTROL_FLAGS operator| (RX_GLOBAL_CONTROL_FLAGS l, RX_GLOBAL_CONTROL_FLAGS r) noexcept
constexpr RX_GLOBAL_CONTROL_FLAGS & operator|= (RX_GLOBAL_CONTROL_FLAGS &l, RX_GLOBAL_CONTROL_FLAGS r) noexcept
template<typename T >
constexpr auto IsMissingTransducer (T x, T y)
std::ostream & operator<< (std::ostream &os, const FirmwareInfo &obj)
template<typename V >
Vector3 ToVector3 (const V &v)
template<typename T >
OkType< T > Ok (T t)
template<typename T >
ErrType< T > Err (T t)
Variables
constexpr size_t FRAME_PADDING_SIZE = 125
constexpr size_t NUM_TRANS_IN_UNIT = 249
constexpr size_t NUM_TRANS_X = 18
constexpr size_t NUM_TRANS_Y = 14
constexpr Float TRANS_SIZE_MM = static_cast<Float>(10.16)
constexpr Float AUTD_WIDTH = static_cast<Float>(192.0)
constexpr Float AUTD_HEIGHT = static_cast<Float>(151.4)
constexpr Float PI = static_cast<Float>(3.14159265358979323846)
constexpr uint32_t FPGA_BASE_CLK_FREQ = 50000000
constexpr uint32_t FPGA_BASE_CLK_PERIOD_NS = 1000000000 / FPGA_BASE_CLK_FREQ
constexpr uint8_t CMD_READ_CPU_VER_LSB = 0x02
constexpr uint8_t CMD_READ_CPU_VER_MSB = 0x03
constexpr uint8_t CMD_READ_FPGA_VER_LSB = 0x04
constexpr uint8_t CMD_READ_FPGA_VER_MSB = 0x05
constexpr uint8_t CMD_CLEAR = 0x09
constexpr uint8_t CMD_ULTRASOUND_CYCLE_CNT = 0x0B
constexpr uint8_t CMD_WRITE_DUTY = 0x10
constexpr uint8_t CMD_WRITE_PHASE = 0x11
constexpr size_t HEADER_SIZE = 128
constexpr size_t EC_OUTPUT_FRAME_SIZE = 626
constexpr size_t EC_INPUT_FRAME_SIZE = 2
constexpr uint32_t EC_SM3_CYCLE_TIME_MICRO_SEC = 1000
constexpr uint32_t EC_SM3_CYCLE_TIME_NANO_SEC = EC_SM3_CYCLE_TIME_MICRO_SEC * 1000
constexpr size_t EC_DEVICE_PER_FRAME = 2
constexpr size_t EC_FRAME_LENGTH = 14 + 2 + (10 + EC_OUTPUT_FRAME_SIZE + EC_INPUT_FRAME_SIZE + 2) * EC_DEVICE_PER_FRAME + 10
constexpr double EC_SPEED_BPS = 100.0 * 1000 * 1000
constexpr double EC_TRAFFIC_DELAY = EC_FRAME_LENGTH * 8 / EC_SPEED_BPS
Typedef Documentation
AUTDDataArray
using autd::AUTDDataArray = typedef std::array<uint16_t, NUM_TRANS_IN_UNIT>
Definition at line 38 of file consts.hpp.
ControllerPtr
using autd::ControllerPtr = typedef unique_ptr<Controller>
Definition at line 35 of file controller.hpp.
Float
using autd::Float = typedef float
Definition at line 19 of file autd_types.hpp.
GainPtr
using autd::GainPtr = typedef std::shared_ptr<Gain>
Definition at line 28 of file gain.hpp.
LinkPtr
using autd::LinkPtr = typedef std::unique_ptr<Link>
Definition at line 65 of file link.hpp.
Matrix4X4
using autd::Matrix4X4 = typedef utils::Matrix4X4<Float>
Definition at line 23 of file linalg.hpp.
NullGain
using autd::NullGain = typedef Gain
Definition at line 106 of file gain.hpp.
Quaternion
using autd::Quaternion = typedef utils::Quaternion<Float>
Definition at line 24 of file linalg.hpp.
Vector3
using autd::Vector3 = typedef utils::Vector3<Float>
Definition at line 21 of file linalg.hpp.
Vector4
using autd::Vector4 = typedef utils::Vector4<Float>
Definition at line 22 of file linalg.hpp.
Enumeration Type Documentation
RX_GLOBAL_CONTROL_FLAGS
enum autd::RX_GLOBAL_CONTROL_FLAGS : uint8_t strong
Enumerator
NONE
FORCE_FAN
Definition at line 22 of file autd_types.hpp.
Function Documentation
Err()
template<typename T > ErrType<T> autd::Err (T t)
Definition at line 85 of file result.hpp.
Referenced by autd::Controller::firmware_info_list().
IsMissingTransducer()
template<typename T > constexpr auto autd::IsMissingTransducer (T x, T y) constexpr
Definition at line 31 of file consts.hpp.
Referenced by autd::Device::Create().
Ok()
template<typename T > OkType<T> autd::Ok (T t)
Definition at line 80 of file result.hpp.
Referenced by autd::Gain::Build(), autd::Controller::Close(), and autd::Controller::firmware_info_list().
operator<<()
std::ostream& autd::operator<< (std::ostream & os, const FirmwareInfo & obj) inline
Definition at line 70 of file firmware_version.hpp.
References autd::FirmwareInfo::cpu_version(), and autd::FirmwareInfo::fpga_version().
operator|()
constexpr RX_GLOBAL_CONTROL_FLAGS autd::operator| (RX_GLOBAL_CONTROL_FLAGS l, RX_GLOBAL_CONTROL_FLAGS r) constexpr noexcept
Definition at line 31 of file autd_types.hpp.
operator|=()
constexpr RX_GLOBAL_CONTROL_FLAGS& autd::operator|= (RX_GLOBAL_CONTROL_FLAGS & l, RX_GLOBAL_CONTROL_FLAGS r) constexpr noexcept
Definition at line 36 of file autd_types.hpp.
ToVector3()
template<typename V > Vector3 autd::ToVector3 (const V & v)
Definition at line 27 of file linalg.hpp.
Referenced by autd::Device::Create().
Variable Documentation
AUTD_HEIGHT
constexpr Float autd::AUTD_HEIGHT = static_cast<Float>(151.4) constexpr
Definition at line 26 of file consts.hpp.
AUTD_WIDTH
constexpr Float autd::AUTD_WIDTH = static_cast<Float>(192.0) constexpr
Definition at line 25 of file consts.hpp.
CMD_CLEAR
constexpr uint8_t autd::CMD_CLEAR = 0x09 constexpr
Definition at line 41 of file controller.hpp.
Referenced by autd::Controller::Clear().
CMD_READ_CPU_VER_LSB
constexpr uint8_t autd::CMD_READ_CPU_VER_LSB = 0x02 constexpr
Definition at line 37 of file controller.hpp.
Referenced by autd::Controller::firmware_info_list().
CMD_READ_CPU_VER_MSB
constexpr uint8_t autd::CMD_READ_CPU_VER_MSB = 0x03 constexpr
Definition at line 38 of file controller.hpp.
Referenced by autd::Controller::firmware_info_list().
CMD_READ_FPGA_VER_LSB
constexpr uint8_t autd::CMD_READ_FPGA_VER_LSB = 0x04 constexpr
Definition at line 39 of file controller.hpp.
Referenced by autd::Controller::firmware_info_list().
CMD_READ_FPGA_VER_MSB
constexpr uint8_t autd::CMD_READ_FPGA_VER_MSB = 0x05 constexpr
Definition at line 40 of file controller.hpp.
Referenced by autd::Controller::firmware_info_list().
CMD_ULTRASOUND_CYCLE_CNT
constexpr uint8_t autd::CMD_ULTRASOUND_CYCLE_CNT = 0x0B constexpr
Definition at line 42 of file controller.hpp.
CMD_WRITE_DUTY
constexpr uint8_t autd::CMD_WRITE_DUTY = 0x10 constexpr
Definition at line 43 of file controller.hpp.
CMD_WRITE_PHASE
constexpr uint8_t autd::CMD_WRITE_PHASE = 0x11 constexpr
Definition at line 44 of file controller.hpp.
EC_DEVICE_PER_FRAME
constexpr size_t autd::EC_DEVICE_PER_FRAME = 2 constexpr
Definition at line 22 of file ec_config.hpp.
EC_FRAME_LENGTH
constexpr size_t autd::EC_FRAME_LENGTH = 14 + 2 + (10 + EC_OUTPUT_FRAME_SIZE + EC_INPUT_FRAME_SIZE + 2) * EC_DEVICE_PER_FRAME + 10 constexpr
Definition at line 23 of file ec_config.hpp.
EC_INPUT_FRAME_SIZE
constexpr size_t autd::EC_INPUT_FRAME_SIZE = 2 constexpr
Definition at line 17 of file ec_config.hpp.
EC_OUTPUT_FRAME_SIZE
constexpr size_t autd::EC_OUTPUT_FRAME_SIZE = 626 constexpr
Definition at line 16 of file ec_config.hpp.
EC_SM3_CYCLE_TIME_MICRO_SEC
constexpr uint32_t autd::EC_SM3_CYCLE_TIME_MICRO_SEC = 1000 constexpr
Definition at line 19 of file ec_config.hpp.
EC_SM3_CYCLE_TIME_NANO_SEC
constexpr uint32_t autd::EC_SM3_CYCLE_TIME_NANO_SEC = EC_SM3_CYCLE_TIME_MICRO_SEC * 1000 constexpr
Definition at line 20 of file ec_config.hpp.
EC_SPEED_BPS
constexpr double autd::EC_SPEED_BPS = 100.0 * 1000 * 1000 constexpr
Definition at line 24 of file ec_config.hpp.
EC_TRAFFIC_DELAY
constexpr double autd::EC_TRAFFIC_DELAY = EC_FRAME_LENGTH * 8 / EC_SPEED_BPS constexpr
Definition at line 25 of file ec_config.hpp.
FPGA_BASE_CLK_FREQ
constexpr uint32_t autd::FPGA_BASE_CLK_FREQ = 50000000 constexpr
Definition at line 35 of file consts.hpp.
FPGA_BASE_CLK_PERIOD_NS
constexpr uint32_t autd::FPGA_BASE_CLK_PERIOD_NS = 1000000000 / FPGA_BASE_CLK_FREQ constexpr
Definition at line 36 of file consts.hpp.
FRAME_PADDING_SIZE
constexpr size_t autd::FRAME_PADDING_SIZE = 125 constexpr
Definition at line 41 of file autd_types.hpp.
HEADER_SIZE
constexpr size_t autd::HEADER_SIZE = 128 constexpr
Definition at line 15 of file ec_config.hpp.
NUM_TRANS_IN_UNIT
constexpr size_t autd::NUM_TRANS_IN_UNIT = 249 constexpr
Definition at line 21 of file consts.hpp.
Referenced by autd::Device::Create().
NUM_TRANS_X
constexpr size_t autd::NUM_TRANS_X = 18 constexpr
Definition at line 22 of file consts.hpp.
Referenced by autd::Device::Create().
NUM_TRANS_Y
constexpr size_t autd::NUM_TRANS_Y = 14 constexpr
Definition at line 23 of file consts.hpp.
Referenced by autd::Device::Create().
PI
constexpr Float autd::PI = static_cast<Float>(3.14159265358979323846) constexpr
Definition at line 28 of file consts.hpp.
Referenced by autd::utils::Vector3< Float >::angle(), and autd::Gain::ToDuty().
TRANS_SIZE_MM
constexpr Float autd::TRANS_SIZE_MM = static_cast<Float>(10.16) constexpr
Definition at line 24 of file consts.hpp.
Referenced by autd::Device::Create().