autd3-freq-shift: autd::utils Namespace Reference
autd::utils Namespace Reference
Classes
class LinalgHelper
class Matrix4X4
struct MatrixX
class Quaternion
Simple quaternion class.
class Vector3
class Vector4
struct VectorX
Functions
template<typename T >
std::ostream & operator<< (std::ostream &os, const MatrixX< T > &obj)
template<typename T >
bool operator== (const MatrixX< T > &lhs, const MatrixX< T > &rhs)
template<typename T >
bool operator!= (const MatrixX< T > &lhs, const MatrixX< T > &rhs)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Quaternion< T > &obj)
template<typename T >
bool operator== (const Quaternion< T > &lhs, const Quaternion< T > &rhs)
template<typename T >
bool operator!= (const Quaternion< T > &lhs, const Quaternion< T > &rhs)
template<typename T >
std::ostream & operator<< (std::ostream &os, const VectorX< T > &obj)
template<typename T >
bool operator== (const VectorX< T > &lhs, const VectorX< T > &rhs)
template<typename T >
bool operator!= (const VectorX< T > &lhs, const VectorX< T > &rhs)
Function Documentation
operator!=() [1/3]
template<typename T > bool autd::utils::operator!= (const MatrixX< T > & lhs, const MatrixX< T > & rhs)
Definition at line 110 of file matrix.hpp.
operator!=() [2/3]
template<typename T > bool autd::utils::operator!= (const Quaternion< T > & lhs, const Quaternion< T > & rhs)
Definition at line 163 of file quaternion.hpp.
operator!=() [3/3]
template<typename T > bool autd::utils::operator!= (const VectorX< T > & lhs, const VectorX< T > & rhs)
Definition at line 103 of file vector.hpp.
operator<<() [1/3]
template<typename T > std::ostream& autd::utils::operator<< (std::ostream & os, const MatrixX< T > & obj)
Definition at line 102 of file matrix.hpp.
References autd::utils::LinalgHelper::mat_show().
operator<<() [2/3]
template<typename T > std::ostream& autd::utils::operator<< (std::ostream & os, const Quaternion< T > & obj)
Definition at line 154 of file quaternion.hpp.
References autd::utils::Quaternion< T >::w(), autd::utils::Quaternion< T >::x(), autd::utils::Quaternion< T >::y(), and autd::utils::Quaternion< T >::z().
operator<<() [3/3]
template<typename T > std::ostream& autd::utils::operator<< (std::ostream & os, const VectorX< T > & obj)
Definition at line 95 of file vector.hpp.
operator==() [1/3]
template<typename T > bool autd::utils::operator== (const MatrixX< T > & lhs, const MatrixX< T > & rhs)
Definition at line 106 of file matrix.hpp.
References autd::utils::LinalgHelper::mat_equals().
operator==() [2/3]
template<typename T > bool autd::utils::operator== (const Quaternion< T > & lhs, const Quaternion< T > & rhs)
Definition at line 159 of file quaternion.hpp.
References autd::utils::Quaternion< T >::v(), and autd::utils::Quaternion< T >::w().
operator==() [3/3]
template<typename T > bool autd::utils::operator== (const VectorX< T > & lhs, const VectorX< T > & rhs)
Definition at line 99 of file vector.hpp.