autd3-freq-shift: autd::Device Struct Reference
autd::Device Struct Reference
#include <device.hpp>
Public Member Functions
Vector3 x_direction ()
Vector3 y_direction ()
Vector3 z_direction ()
std::unique_ptr< Vector3[]> & global_trans_positions ()
Static Public Member Functions
static Device Create (const Vector3 &position, const Quaternion &quaternion)
static Device Create (const Vector3 &position, const Vector3 &euler_angles)
Detailed Description
Definition at line 22 of file device.hpp.
Member Function Documentation
Create() [1/2]
static Device autd::Device::Create (const Vector3 & position, const Quaternion & quaternion) inline static
Definition at line 23 of file device.hpp.
References global_trans_positions(), autd::IsMissingTransducer(), autd::NUM_TRANS_IN_UNIT, autd::NUM_TRANS_X, autd::NUM_TRANS_Y, autd::ToVector3(), autd::TRANS_SIZE_MM, autd::utils::Matrix4X4< T >::Translation(), x_direction(), y_direction(), and z_direction().
Referenced by Create().
Create() [2/2]
static Device autd::Device::Create (const Vector3 & position, const Vector3 & euler_angles) inline static
Definition at line 43 of file device.hpp.
References autd::utils::Quaternion< T >::AngleAxis(), Create(), autd::utils::Vector3< Float >::UnitY(), autd::utils::Vector3< Float >::UnitZ(), autd::utils::Vector3< T >::x(), autd::utils::Vector3< T >::y(), and autd::utils::Vector3< T >::z().
global_trans_positions()
std::unique_ptr<Vector3[]>& autd::Device::global_trans_positions () inline
Definition at line 53 of file device.hpp.
Referenced by Create().
x_direction()
Vector3 autd::Device::x_direction () inline
Definition at line 50 of file device.hpp.
Referenced by Create().
y_direction()
Vector3 autd::Device::y_direction () inline
Definition at line 51 of file device.hpp.
Referenced by Create().
z_direction()
Vector3 autd::Device::z_direction () inline
Definition at line 52 of file device.hpp.
Referenced by Create().
The documentation for this struct was generated from the following file:
include/device.hpp