autd3-freq-shift: autd::utils::VectorX< T > Struct Template Reference
autd::utils::VectorX< T > Struct Template Reference
#include <vector.hpp>
Public Member Functions
VectorX (const size_t size)
~VectorX ()=default
VectorX (const VectorX &obj)
VectorX & operator= (VectorX &obj)=delete
VectorX (VectorX &&obj) noexcept
VectorX & operator= (VectorX &&obj) noexcept
T l2_norm_squared () const
T l2_norm () const
T norm () const
void normalize ()
VectorX & normalized () const
T dot (const VectorX &rhs) const
T & at (size_t i)
const T & at (size_t i) const
T & operator() (size_t i)
const T & operator() (size_t i) const
T * data ()
const T * data () const
size_t size () const noexcept
VectorX & operator+= (const VectorX &rhs)
VectorX & operator-= (const VectorX &rhs)
VectorX & operator*= (T rhs)
VectorX & operator/= (T rhs)
VectorX operator- () const
Static Public Member Functions
static VectorX Zero (size_t size)
static VectorX Ones (size_t size)
Friends
VectorX operator+ (const VectorX &lhs, const VectorX &rhs)
VectorX operator- (const VectorX &lhs, const VectorX &rhs)
VectorX operator* (const VectorX &lhs, const T &rhs)
VectorX operator* (const T &lhs, const VectorX &rhs)
VectorX operator/ (const VectorX &lhs, const T &rhs)
Detailed Description
template<typename T>
struct autd::utils::VectorX< T >
Definition at line 24 of file vector.hpp.
Constructor & Destructor Documentation
VectorX() [1/3]
template<typename T > autd::utils::VectorX< T >::VectorX (const size_t size) inline explicit
Definition at line 25 of file vector.hpp.
~VectorX()
template<typename T > autd::utils::VectorX< T >::~VectorX () default
VectorX() [2/3]
template<typename T > autd::utils::VectorX< T >::VectorX (const VectorX< T > & obj) inline
Definition at line 27 of file vector.hpp.
VectorX() [3/3]
template<typename T > autd::utils::VectorX< T >::VectorX (VectorX< T > && obj) inline noexcept
Definition at line 35 of file vector.hpp.
Member Function Documentation
at() [1/2]
template<typename T > T& autd::utils::VectorX< T >::at (size_t i) inline
Definition at line 65 of file vector.hpp.
at() [2/2]
template<typename T > const T& autd::utils::VectorX< T >::at (size_t i) const inline
Definition at line 66 of file vector.hpp.
data() [1/2]
template<typename T > T* autd::utils::VectorX< T >::data () inline
Definition at line 71 of file vector.hpp.
Referenced by autd::utils::MatrixX< T >::row(), and autd::utils::VectorX< Float >::Zero().
data() [2/2]
template<typename T > const T* autd::utils::VectorX< T >::data () const inline
Definition at line 72 of file vector.hpp.
dot()
template<typename T > T autd::utils::VectorX< T >::dot (const VectorX< T > & rhs) const inline
Definition at line 63 of file vector.hpp.
l2_norm()
template<typename T > T autd::utils::VectorX< T >::l2_norm () const inline
Definition at line 45 of file vector.hpp.
Referenced by autd::utils::Vector3< Float >::angle(), autd::utils::VectorX< Float >::norm(), autd::utils::VectorX< Float >::normalize(), and autd::utils::VectorX< Float >::normalized().
l2_norm_squared()
template<typename T > T autd::utils::VectorX< T >::l2_norm_squared () const inline
Definition at line 44 of file vector.hpp.
Referenced by autd::utils::VectorX< Float >::l2_norm(), and autd::utils::Quaternion< T >::l2_norm_squared().
norm()
template<typename T > T autd::utils::VectorX< T >::norm () const inline
Definition at line 46 of file vector.hpp.
normalize()
template<typename T > void autd::utils::VectorX< T >::normalize () inline
Definition at line 48 of file vector.hpp.
normalized()
template<typename T > VectorX& autd::utils::VectorX< T >::normalized () const inline
Definition at line 49 of file vector.hpp.
Ones()
template<typename T > static VectorX autd::utils::VectorX< T >::Ones (size_t size) inline static
Definition at line 57 of file vector.hpp.
operator()() [1/2]
template<typename T > T& autd::utils::VectorX< T >::operator() (size_t i) inline
Definition at line 68 of file vector.hpp.
operator()() [2/2]
template<typename T > const T& autd::utils::VectorX< T >::operator() (size_t i) const inline
Definition at line 69 of file vector.hpp.
operator*=()
template<typename T > VectorX& autd::utils::VectorX< T >::operator*= (T rhs) inline
Definition at line 78 of file vector.hpp.
operator+=()
template<typename T > VectorX& autd::utils::VectorX< T >::operator+= (const VectorX< T > & rhs) inline
Definition at line 76 of file vector.hpp.
operator-()
template<typename T > VectorX autd::utils::VectorX< T >::operator- () const inline
Definition at line 81 of file vector.hpp.
operator-=()
template<typename T > VectorX& autd::utils::VectorX< T >::operator-= (const VectorX< T > & rhs) inline
Definition at line 77 of file vector.hpp.
operator/=()
template<typename T > VectorX& autd::utils::VectorX< T >::operator/= (T rhs) inline
Definition at line 79 of file vector.hpp.
operator=() [1/2]
template<typename T > VectorX& autd::utils::VectorX< T >::operator= (VectorX< T > && obj) inline noexcept
Definition at line 36 of file vector.hpp.
operator=() [2/2]
template<typename T > VectorX& autd::utils::VectorX< T >::operator= (VectorX< T > & obj) delete
size()
template<typename T > size_t autd::utils::VectorX< T >::size () const inline noexcept
Definition at line 74 of file vector.hpp.
Referenced by autd::utils::VectorX< Float >::Ones(), autd::utils::VectorX< Float >::VectorX(), and autd::utils::VectorX< Float >::Zero().
Zero()
template<typename T > static VectorX autd::utils::VectorX< T >::Zero (size_t size) inline static
Definition at line 51 of file vector.hpp.
Friends And Related Function Documentation
operator* [1/2]
template<typename T > VectorX operator* (const T & lhs, const VectorX< T > & rhs) friend
Definition at line 86 of file vector.hpp.
operator* [2/2]
template<typename T > VectorX operator* (const VectorX< T > & lhs, const T & rhs) friend
Definition at line 85 of file vector.hpp.
operator+
template<typename T > VectorX operator+ (const VectorX< T > & lhs, const VectorX< T > & rhs) friend
Definition at line 83 of file vector.hpp.
operator-
template<typename T > VectorX operator- (const VectorX< T > & lhs, const VectorX< T > & rhs) friend
Definition at line 84 of file vector.hpp.
operator/
template<typename T > VectorX operator/ (const VectorX< T > & lhs, const T & rhs) friend
Definition at line 87 of file vector.hpp.
The documentation for this struct was generated from the following file:
include/linalg/vector.hpp