name: 'Doxygen Action with CMake'
inputs:
  cmake-proj-path:
    description: 'Path to CMake project dir'
    required: true
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmake-proj-path }}
    - ${{ inputs.working-directory }}